/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Forca: typeof import('./src/components/Forca.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JogoDaForca: typeof import('./src/components/JogoDaForca.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teclado: typeof import('./src/components/Teclado.vue')['default']
  }
}
